### ISSUE TITLE
Crash when building window

### ISSUE THREAD

**Issue by csherratt** [tomaka/glutin#534]
All the examples seem to be crash for me right now.

I bisected the regression down to [this change](https://github.com/tomaka/glutin/pull/530).

backtrace of crash:
```
#0  0x00007ffff4f8e154 in glXGetFBConfigAttrib () from /usr/lib/nvidia-346/libGL.so.1
#1  0x000055555559b19b in glutin::api::x11::ffi::glx::Glx::GetFBConfigAttrib (self=0x7fffffff75d8, dpy=0x555555998910, 
    config=0x7ffff7dd3c58 <main_arena+88>, attribute=32, value=0x7fffffff6cbc)
    at target/debug/build/glutin-96902c15579b5552/out/glx_bindings.rs:650
#2  0x000055555559b0ef in fnfn (attrib=32, fb_config=0x7ffff7dd3c58 <main_arena+88>) at src/api/glx/mod.rs:354
#3  0x000055555559b94d in fnfn (config=0x7ffff7dd3c58 <main_arena+88>) at src/api/glx/mod.rs:360
#4  0x000055555559b809 in glutin::iter::FilterMap<I, F>.Iterator::next (self=0x7fffffff7020) at ../src/libcore/iter.rs:1806
#5  0x000055555559b345 in glutin::vec::Vec<T>.FromIterator<T>::from_iter<core::iter::FilterMap<collections::vec::IntoIter<*const libc::types::common::c95::c_void>, closure>> (iterable=...) at ../src/libcollections/vec.rs:1481
#6  0x000055555559b241 in glutin::iter::Iterator::collect<core::iter::FilterMap<collections::vec::IntoIter<*const libc::types::common::c95::c_void>, closure>,collections::vec::Vec<(*const libc::types::common::c95::c_void, glutin::PixelFormat)>> (self=...)
    at ../src/libcore/iter.rs:563
#7  0x0000555555594c74 in glutin::api::glx::enumerate_configs (glx=0x7fffffff75d8, xlib=0x7ffff682f010, display=0x555555998910)
    at src/api/glx/mod.rs:359
#8  0x000055555559437b in glutin::api::glx::Context::new (glx=..., xlib=0x7ffff682f010, builder=0x7fffffffad80, display=0x555555998910)
    at src/api/glx/mod.rs:43
#9  0x00005555555ce9a7 in glutin::api::x11::window::Window::new (display=0x7ffff6823008, builder=...) at src/api/x11/window.rs:338
#10 0x00005555555d98ff in glutin::platform::platform::api_dispatch::Window::new (builder=...) at src/platform/linux/api_dispatch.rs:155
#11 0x00005555555e0340 in glutin::window::WindowBuilder<'a>::build (self=...) at src/window.rs:182
#12 0x00005555555740fa in window::main () at examples/window.rs:22
#13 0x00005555556a4dc9 in rust_try_inner ()
#14 0x00005555556a4db6 in rust_try ()
#15 0x00005555556a1a69 in rt::lang_start::h5cc45221c651f24bi3w ()
#16 0x000055555557bc4c in main ()
```

Tested running Ubuntu 15.04 with Nvidia 346 drivers.

**Comment by tomaka** [comment]
Oh.

It may be coming from the fact that we're potentially passing an invalid enum.
I was relying on the fact that the function returns an error in this situation.

**Comment by tomaka** [comment]
Could you run `glxinfo | grep GLX_EXT_visual_rating` and see if something is found?

**Comment by tomaka** [comment]
Hmmm, in fact it would be weird if it wasn't supported by such a recent driver.
Do you happen to have multiple screens? That could be the cause.

**Comment by rubendv** [comment]
I encounter the same bug on Ubuntu 14.04 with kernel 3.13 and nvidia-331-updates driver. I am using a dual screen setup.

**Comment by rubendv** [comment]
This is the output when running `glxinfo | grep GLX_EXT_visual_rating`:
```
GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
```

**Comment by tomaka** [comment]
After some investigation, I have two hypotheses:

 - The bug that was fixed by #536 
 - Glutin tries to read from a FBConfig that doesn't have an associated visual (which I didn't know was possible).

**Comment by rubendv** [comment]
The issue is still there when I use the latest master, so it appears the first one is not what was causing it.

**Comment by tomaka** [comment]
PR #537 should fix the second one.

**Comment by rubendv** [comment]
Okay so I was wrong in my previous comment, I used the latest master of glium, not glutin. The latest master gives this result:

```
% cargo run --example window                                                                 :(
     Running `target/debug/examples/window`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: XNotSupported', ../src/libcore/result.rs:731
An unknown error occurred

To learn more, run the command again with --verbose.
%
```

So the first fix appears to have fixed the segfault, and replaced it with a panic.
PR #537 does not compile for me on latest rust nightly:

```
% cargo run --example window                                                             :(
   Compiling glutin v0.3.2 (...)
src/api/glx/mod.rs:362:21: 362:22 error: `continue` inside of a closure [E0267]
src/api/glx/mod.rs:362             continue;
                                           ^
note: in expansion of closure expansion
src/api/glx/mod.rs:360:39: 398:6 note: expansion site
src/api/glx/mod.rs:362:21: 362:22 help: run `rustc --explain E0267` to see a detailed explanation
src/api/glx/mod.rs:366:21: 366:22 error: `continue` inside of a closure [E0267]
src/api/glx/mod.rs:366             continue;
                                           ^
note: in expansion of closure expansion
src/api/glx/mod.rs:360:39: 398:6 note: expansion site
src/api/glx/mod.rs:366:21: 366:22 help: run `rustc --explain E0267` to see a detailed explanation
src/api/glx/mod.rs:370:21: 370:22 error: `continue` inside of a closure [E0267]
src/api/glx/mod.rs:370             continue;
                                           ^
note: in expansion of closure expansion
src/api/glx/mod.rs:360:39: 398:6 note: expansion site
src/api/glx/mod.rs:370:21: 370:22 help: run `rustc --explain E0267` to see a detailed explanation
error: aborting due to 3 previous errors
Could not compile `glutin`.

To learn more, run the command again with --verbose.
%
```

**Comment by rubendv** [comment]
First error message should be this instead of the above:
```
% cargo run --example window                                                                                                                                                                            :(
     Running `target/debug/examples/window`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("glxGetVisualFromFBConfig failed")', ../src/libcore/result.rs:731
An unknown error occurred

To learn more, run the command again with --verbose.
%
```

The XNotSupported error above was caused by doing it over ssh.

**Comment by tomaka** [comment]
Ah so the crash was indeed due to reading data after calling `XFree`.

I fixed #537, which should fix `glxGetVisualFromFBConfig failed`.

**Comment by rubendv** [comment]
It appears to be fixed now.
